# Generated by Django 4.2 on 2024-07-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0002_remove_responsetimecreate_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetimecreate',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='responsetimecreate',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsetimedelete',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='responsetimedelete',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
